spring:
  application:
    name: microservice-a

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

microserviceB:
  url:
    getInfo: http://MICROSERVICE-B/app/getInfo

microserviceC:
  url:
    getInfo: http://MICROSERVICE-C/app/getInfo

microserviceD:
  url:
    getInfo: http://MICROSERVICE-D/app/getInfo

microserviceE:
  url:
    getInfo: http://MICROSERVICE-E/app/getInfo
